version: '3.4'

services:
    mssql:
        container_name: mssql-server
        image: mcr.microsoft.com/mssql/server:latest
        environment:
            - SA_PASSWORD=Pa$$w0rd
            - ACCEPT_EULA=Y
        ports:
            - 5432:1433
    myassistant.core.api:
        container_name: myassistant-core
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=4141
            - ASPNETCORE_HTTPS_PORTS=24141
        ports:
            - "4141"
            - "24141"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro